<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
    <RootNamespace>AIrCon.BasicPlugin</RootNamespace>
    <AssemblyName>AIrCon.BasicPlugin</AssemblyName>
    <Version>1.0.2</Version>
    <FileVersion>1.0.2.0</FileVersion>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <InformationalVersion>1.0.2</InformationalVersion>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="AIrCon.ico">
      <LogicalName>AIrCon.ico</LogicalName>
    </EmbeddedResource>
    <Content Include="AIrCon.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TvAIrPlugin\TvAIrPlugin.csproj" Private="false" />
  </ItemGroup>
</Project>
