<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
    <RootNamespace>AIrCon.BasicPlugin</RootNamespace>
    <AssemblyName>AIrCon.BasicPlugin</AssemblyName>
    <Version>1.0.1</Version>
    <FileVersion>1.0.1.0</FileVersion>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="AIrCon.ico">
      <LogicalName>AIrCon.ico</LogicalName>
    </EmbeddedResource>
    <Content Include="AIrCon.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TvAIrPlugin\TvAIrPlugin.csproj" Private="false" />
  </ItemGroup>
  <Target Name="EnsureRestoreAssets" BeforeTargets="PrepareForBuild" Condition="!Exists('$(ProjectAssetsFile)')">
    <MSBuild Projects="$(MSBuildProjectFullPath)" Targets="Restore" Properties="Configuration=$(Configuration);Platform=$(Platform)" />
  </Target>
</Project>
